library(here)
library(dplyr)
data <- read.csv(here("FinalDataset.csv"), header = TRUE)
filtered_data <- data %>% filter(year == 2017)
names(filtered_data)
missing <- is.na(filtered_data$MaternalMortalityRate)
sum(missing)
newdnomiss <- filtered_data %>% filter(!is.na(MaternalMortalityRate))
a1 <- newdnomiss%>% filter(armconf1 == 1)
a2 <- newdnomiss%>% filter(armconf1 == 0)
median(a1$MaternalMortalityRate)