---
title: "Table1 & Figure Trend"
format: pdf
editor: visual
---

**Table 1**

```{r}
#| echo: FALSE
library(tidyverse)
library(table1)
library(here)
data <- read.csv(here("merged_all_con.csv"), header = TRUE)
data$armconf1 <- ifelse(is.na(data$armconf1), 0, data$armconf1)
base <- data %>% filter(year == 2000)

base$armconf1new <- factor(base$armconf1, levels = c(0,1), labels = c("No armed conflict in 2000", "Armed conflict in 2000"))
base$droughtnew <- factor(base$drought, levels = c(0,1), labels = c("No", "Yes"))
base$earthquakenew <- factor(base$earthquake, levels = c(0,1), labels = c("No", "Yes"))
base$OECDnew <- factor(base$OECD, levels = c(0,1), labels = c("No", "Yes"))

label(base$gdp1000)       <- "GDP per capita (USD)"
label(base$OECDnew)       <- "OECD member"
label(base$popdens)       <- "Population density"
label(base$urban)         <- "Urban residence"
label(base$agedep)        <- "Age dependency ratio"
label(base$male_edu)      <- "Male education"
label(base$temp)          <- "Mean annual temperature"
label(base$rainfall1000)  <- "Mean annual rain fall"
label(base$earthquakenew)   <- "Earthquake"
label(base$droughtnew)      <- "Drought"
label(base$armconf1new)     <- "Armed conflict"



table1(~ gdp1000 + OECDnew + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquakenew + droughtnew| armconf1new, data = base,
        render.continuous = c(.="Median [Min, Max]"),
       overall=c(left="Total"))
```

**Figure: Maternal Mortality Rate Trend from 2000 to 2017**

\*(We don't consider 2018 and 2019 because we have missing maternal mortality rate for both years)

```{r}
library(tidyverse)
library(table1)
library(here)
library(dplyr)
data <- read.csv(here("merged_all_con.csv"), header = TRUE)
figure<- data |> select(country_name, ISO, year, MaternalMortalityRate) |>
  filter(year < 2018) |>
  arrange(ISO, year) |>
  group_by(ISO) |>
  mutate(diffmatmor = MaternalMortalityRate- MaternalMortalityRate[1L]) |>
  arrange(ISO, desc(year)) |>
  mutate(incmatmor = ifelse(diffmatmor[1L] > 0 , 1, 0)) |>
  arrange(ISO, year) |>
  ungroup() |>
  filter(incmatmor == 1)

length(unique(figure$ISO))

fig1 <- figure |>
  ggplot(aes(x = year, y = MaternalMortalityRate, group = ISO)) +
  geom_line(aes(color = country_name), alpha = 1, linewidth = 1) +
  xlim(c(2000,2017)) +
  # use log 10 sclae for y axis
  scale_y_continuous(trans='log10') + 
  labs(y = "Maternal mortality (log 210 scale)", x = "Year", color = "Country", title = "Trend in maternal mortality for countries that had an increase from 2000 to 2017") + 
  # use black and white theme and increase the size of labels
  theme_bw(base_size = 12)

# save the gplot as a png file
ggsave(fig1, file = here("figure", "fig1.png"), width = 8, height = 5)
```
